[tool.poetry]
name = "homework-2"
version = "1.0.0"
description = ""
authors = ["Denys Kotsiuba  <denis.kotsiuba@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
inquirer = "3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
